services:
  #backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: brain-ag-api
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/usr/src/app
    environment:
      NODE_ENV: development
    networks:
      - backend-network
  db:
    image: postgres:latest
    container_name: brain-ag-postgres
    volumes:
      - ./docker/postgresql/dbdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: brain_ag
      POSTGRES_PASSWORD: brain_ag 
      POSTGRES_DB: brain_ag  
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
